<?php
namespace App\Transformers;

use Acme\Model\Book;
use League\Fractal;

class ImportDataTransformer extends Fractal\TransformerAbstract
{
	public function transform($data)
	{
	    return [
	        'Change_Type' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Covered_Recipient_Type' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Teaching_Hospital_CCN' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Teaching_Hospital_ID' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Teaching_Hospital_Name' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Physician_Profile_ID' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Physician_First_Name' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Physician_Middle_Name' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Physician_Last_Name' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Physician_Name_Suffix' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Recipient_Primary_Business_Street_Address_Line1' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Recipient_Primary_Business_Street_Address_Line2' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Recipient_City' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Recipient_State' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Recipient_Zip_Code' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Recipient_Country' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Recipient_Province' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Recipient_Postal_Code' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Physician_Primary_Type' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Physician_Specialty' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Physician_License_State_code1' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Physician_License_State_code2' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Physician_License_State_code3' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Physician_License_State_code4' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Physician_License_State_code5' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Total_Amount_of_Payment_USDollars' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Date_of_Payment' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Number_of_Payments_Included_in_Total_Amount' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Form_of_Payment_or_Transfer_of_Value' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Nature_of_Payment_or_Transfer_of_Value' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'City_of_Travel' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'State_of_Travel' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Country_of_Travel' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Physician_Ownership_Indicator' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Third_Party_Payment_Recipient_Indicator' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Valu' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Charity_Indicator' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Third_Party_Equals_Covered_Recipient_Indicator' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Contextual_Information' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Delay_in_Publication_Indicator' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Record_ID' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Dispute_Status_for_Publication' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Related_Product_Indicator' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Covered_or_Noncovered_Indicator_1' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Product_Category_or_Therapeutic_Area_1' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Associated_Drug_or_Biological_NDC_1' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Covered_or_Noncovered_Indicator_2' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Product_Category_or_Therapeutic_Area_2' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Associated_Drug_or_Biological_NDC_2' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Covered_or_Noncovered_Indicator_3' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Product_Category_or_Therapeutic_Area_3' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Associated_Drug_or_Biological_NDC_3' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Covered_or_Noncovered_Indicator_4' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Product_Category_or_Therapeutic_Area_4' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Associated_Drug_or_Biological_NDC_4' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Covered_or_Noncovered_Indicator_5' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Product_Category_or_Therapeutic_Area_5' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Associated_Drug_or_Biological_NDC_5' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Program_Year' => isset($data['Change_Type']) ? $data['Change_Type'] : null,
            'Payment_Publication_Date' => isset($data['Change_Type']) ? $data['Change_Type'] : null
	    ];
	}
}