<?php
namespace App\Transformers;

use Acme\Model\Book;
use League\Fractal;

class ImportDataTransformer extends Fractal\TransformerAbstract
{
	public function transform($data)
	{
	    return [
            'change_type' => isset($data['change_type']) ? $data['change_type'] : null,
            'covered_recipient_type' => isset($data['covered_recipient_type']) ? $data['covered_recipient_type'] : null,
            'teaching_hospital_ccn' => isset($data['teaching_hospital_ccn']) ? $data['teaching_hospital_ccn'] : null,
            'teaching_hospital_id' => isset($data['teaching_hospital_id']) ? $data['teaching_hospital_id'] : null,
            'teaching_hospital_name' => isset($data['teaching_hospital_name']) ? $data['teaching_hospital_name'] : null,
            'physician_profile_id' => isset($data['physician_profile_id']) ? $data['physician_profile_id'] : null,
            'physician_first_name' => isset($data['physician_first_name']) ? $data['physician_first_name'] : null,
            'physician_middle_name' => isset($data['physician_middle_name']) ? $data['physician_middle_name'] : null,
            'physician_last_name' => isset($data['physician_last_name']) ? $data['physician_last_name'] : null,
            'physician_name_suffix' => isset($data['physician_name_suffix']) ? $data['physician_name_suffix'] : null,
            'recipient_primary_business_street_address_line1' => isset($data['recipient_primary_business_street_address_line1']) ? $data['recipient_primary_business_street_address_line1'] : null,
            'recipient_primary_business_street_address_line2' => isset($data['recipient_primary_business_street_address_line2']) ? $data['recipient_primary_business_street_address_line2'] : null,
            'recipient_city' => isset($data['recipient_city']) ? $data['recipient_city'] : null,
            'recipient_state' => isset($data['recipient_state']) ? $data['recipient_state'] : null,
            'recipient_zip_code' => isset($data['recipient_zip_code']) ? $data['recipient_zip_code'] : null,
            'recipient_country' => isset($data['recipient_country']) ? $data['recipient_country'] : null,
            'recipient_province' => isset($data['recipient_province']) ? $data['recipient_province'] : null,
            'recipient_postal_code' => isset($data['recipient_postal_code']) ? $data['recipient_postal_code'] : null,
            'physician_primary_type' => isset($data['physician_primary_type']) ? $data['physician_primary_type'] : null,
            'physician_specialty' => isset($data['physician_specialty']) ? $data['physician_specialty'] : null,
            'physician_license_state_code1' => isset($data['physician_license_state_code1']) ? $data['physician_license_state_code1'] : null,
            'physician_license_state_code2' => isset($data['physician_license_state_code2']) ? $data['physician_license_state_code2'] : null,
            'physician_license_state_code3' => isset($data['physician_license_state_code3']) ? $data['physician_license_state_code3'] : null,
            'physician_license_state_code4' => isset($data['physician_license_state_code4']) ? $data['physician_license_state_code4'] : null,
            'physician_license_state_code5' => isset($data['physician_license_state_code5']) ? $data['physician_license_state_code5'] : null,
            'submitting_applicable_manufacturer_or_applicable_gpo_name' => isset($data['submitting_applicable_manufacturer_or_applicable_gpo_name']) ? $data['submitting_applicable_manufacturer_or_applicable_gpo_name'] : null,
            'applicable_manufacturer_or_applicable_gpo_making_payment_id' => isset($data['applicable_manufacturer_or_applicable_gpo_making_payment_id']) ? $data['applicable_manufacturer_or_applicable_gpo_making_payment_id'] : null,
            'applicable_manufacturer_or_applicable_gpo_making_payment_name' => isset($data['applicable_manufacturer_or_applicable_gpo_making_payment_name']) ? $data['applicable_manufacturer_or_applicable_gpo_making_payment_name'] : null,
            'applicable_manufacturer_or_applicable_gpo_making_payment_state' => isset($data['applicable_manufacturer_or_applicable_gpo_making_payment_name']) ? $data['applicable_manufacturer_or_applicable_gpo_making_payment_name'] : null,
            'applicable_manufacturer_or_applicable_gpo_making_payment_country' => isset($data['applicable_manufacturer_or_applicable_gpo_making_payment_country']) ? $data['applicable_manufacturer_or_applicable_gpo_making_payment_country'] : null,
            'total_amount_of_payment_usdollars' => isset($data['total_amount_of_payment_usdollars']) ? $data['total_amount_of_payment_usdollars'] : null,
            'date_of_payment' => isset($data['date_of_payment']) ? $data['date_of_payment'] : null,
            'number_of_payments_included_in_total_amount' => isset($data['number_of_payments_included_in_total_amount']) ? $data['number_of_payments_included_in_total_amount'] : null,
            'form_of_payment_or_transfer_of_value' => isset($data['form_of_payment_or_transfer_of_value']) ? $data['form_of_payment_or_transfer_of_value'] : null,
            'nature_of_payment_or_transfer_of_value' => isset($data['nature_of_payment_or_transfer_of_value']) ? $data['nature_of_payment_or_transfer_of_value'] : null,
            'city_of_travel' => isset($data['city_of_travel']) ? $data['city_of_travel'] : null,
            'state_of_travel' => isset($data['state_of_travel']) ? $data['state_of_travel'] : null,
            'country_of_travel' => isset($data['country_of_travel']) ? $data['country_of_travel'] : null,
            'physician_ownership_indicator' => isset($data['physician_ownership_indicator']) ? $data['physician_ownership_indicator'] : null,
            'third_party_payment_recipient_indicator' => isset($data['third_party_payment_recipient_indicator']) ? $data['third_party_payment_recipient_indicator'] : null,
            'name_of_third_party_entity_receiving_payment_or_transfer_of_valu' => isset($data['name_of_third_party_entity_receiving_payment_or_transfer_of_value']) ? $data['name_of_third_party_entity_receiving_payment_or_transfer_of_value'] : null,
            'charity_indicator' => isset($data['charity_indicator']) ? $data['charity_indicator'] : null,
            'third_party_equals_covered_recipient_indicator' => isset($data['third_party_equals_covered_recipient_indicator']) ? $data['third_party_equals_covered_recipient_indicator'] : null,
            'contextual_information' => isset($data['contextual_information']) ? $data['contextual_information'] : null,
            'delay_in_publication_indicator' => isset($data['delay_in_publication_indicator']) ? $data['delay_in_publication_indicator'] : null,
            'record_id' => isset($data['record_id']) ? $data['record_id'] : null,
            'dispute_status_for_publication' => isset($data['dispute_status_for_publication']) ? $data['dispute_status_for_publication'] : null,
            'related_product_indicator' => isset($data['change_type']) ? $data['change_type'] : null,
            'covered_or_noncovered_indicator_1' => isset($data['covered_or_noncovered_indicator_1']) ? $data['covered_or_noncovered_indicator_1'] : null,
            'indicate_drug_or_biological_or_device_or_medical_supply_1' => isset($data['indicate_drug_or_biological_or_device_or_medical_supply_1']) ? $data['indicate_drug_or_biological_or_device_or_medical_supply_1'] : null,
            'product_category_or_therapeutic_area_1' => isset($data['product_category_or_therapeutic_area_1']) ? $data['product_category_or_therapeutic_area_1'] : null,
            'name_of_drug_or_biological_or_device_or_medical_supply_1' => isset($data['name_of_drug_or_biological_or_device_or_medical_supply_1']) ? $data['name_of_drug_or_biological_or_device_or_medical_supply_1'] : null,
            'associated_drug_or_biological_ndc_1' => isset($data['associated_drug_or_biological_ndc_1']) ? $data['associated_drug_or_biological_ndc_1'] : null,
            'covered_or_noncovered_indicator_2' => isset($data['covered_or_noncovered_indicator_2']) ? $data['covered_or_noncovered_indicator_2'] : null,
            'indicate_drug_or_biological_or_device_or_medical_supply_2' => isset($data['change_type']) ? $data['change_type'] : null,
            'product_category_or_therapeutic_area_2' => isset($data['product_category_or_therapeutic_area_2']) ? $data['product_category_or_therapeutic_area_2'] : null,
            'name_of_drug_or_biological_or_device_or_medical_supply_2' => isset($data['name_of_drug_or_biological_or_device_or_medical_supply_2']) ? $data['name_of_drug_or_biological_or_device_or_medical_supply_2'] : null,
            'associated_drug_or_biological_ndc_2' => isset($data['associated_drug_or_biological_ndc_2']) ? $data['associated_drug_or_biological_ndc_2'] : null,
            'covered_or_noncovered_indicator_3' => isset($data['covered_or_noncovered_indicator_3']) ? $data['covered_or_noncovered_indicator_3'] : null,
            'indicate_drug_or_biological_or_device_or_medical_supply_3' => isset($data['indicate_drug_or_biological_or_device_or_medical_supply_3']) ? $data['indicate_drug_or_biological_or_device_or_medical_supply_3'] : null,
            'product_category_or_therapeutic_area_3' => isset($data['product_category_or_therapeutic_area_3']) ? $data['product_category_or_therapeutic_area_3'] : null,
            'name_of_drug_or_biological_or_device_or_medical_supply_3' => isset($data['name_of_drug_or_biological_or_device_or_medical_supply_3']) ? $data['name_of_drug_or_biological_or_device_or_medical_supply_3'] : null,
            'associated_drug_or_biological_ndc_3' => isset($data['associated_drug_or_biological_ndc_3']) ? $data['associated_drug_or_biological_ndc_3'] : null,
            'covered_or_noncovered_indicator_4' => isset($data['covered_or_noncovered_indicator_4']) ? $data['covered_or_noncovered_indicator_4'] : null,
            'indicate_drug_or_biological_or_device_or_medical_supply_4' => isset($data['indicate_drug_or_biological_or_device_or_medical_supply_4']) ? $data['indicate_drug_or_biological_or_device_or_medical_supply_4'] : null,
            'product_category_or_therapeutic_area_4' => isset($data['product_category_or_therapeutic_area_4']) ? $data['product_category_or_therapeutic_area_4'] : null,
            'name_of_drug_or_biological_or_device_or_medical_supply_4' => isset($data['name_of_drug_or_biological_or_device_or_medical_supply_4']) ? $data['name_of_drug_or_biological_or_device_or_medical_supply_4'] : null,
            'associated_drug_or_biological_ndc_4' => isset($data['associated_drug_or_biological_ndc_4']) ? $data['associated_drug_or_biological_ndc_4'] : null,
            'covered_or_noncovered_indicator_5' => isset($data['covered_or_noncovered_indicator_5']) ? $data['covered_or_noncovered_indicator_5'] : null,
            'indicate_drug_or_biological_or_device_or_medical_supply_5' => isset($data['indicate_drug_or_biological_or_device_or_medical_supply_5']) ? $data['indicate_drug_or_biological_or_device_or_medical_supply_5'] : null,
            'product_category_or_therapeutic_area_5' => isset($data['product_category_or_therapeutic_area_5']) ? $data['product_category_or_therapeutic_area_5'] : null,
            'name_of_drug_or_biological_or_device_or_medical_supply_5' => isset($data['name_of_drug_or_biological_or_device_or_medical_supply_5']) ? $data['name_of_drug_or_biological_or_device_or_medical_supply_5'] : null,
            'associated_drug_or_biological_ndc_5' => isset($data['associated_drug_or_biological_ndc_5']) ? $data['associated_drug_or_biological_ndc_5'] : null,
            'program_year' => isset($data['program_year']) ? $data['program_year'] : null,
            'payment_publication_date' => isset($data['payment_publication_date']) ? $data['payment_publication_date'] : null
	    ];
	}
}